### ISSUE TITLE
Add ability to sort repositories based on different Criteria

### ISSUE THREAD

**Issue by Ticketedmoon** [Satyam1203/resume-github#4]
This issue should allow two varieties of sorting the repositories. 

The page upon first entry will default to the github user's selected 6 repositories but there can be a dropdown to sort on different criteria.
- The first variant of this will be sorted by star rating
- The second will be sorting by date

**Comment by Satyam1203** [comment]
I'm already on that @ShaneCreedon. I'll open an issue if I need help on that.
