### ISSUE TITLE
Bug: Page throws an error when no links are found in the bio

### ISSUE THREAD

**Issue by Ticketedmoon** [Satyam1203/resume-github#5]
![image](https://user-images.githubusercontent.com/21260839/94958561-a65cfb00-04e7-11eb-9df7-5a8b1d59cb73.png)

The image above shows the lines of code in question - if no links are present, matches becomes null and then when we try to map over it, an NPE is thrown.

**Comment by Ticketedmoon** [comment]
@Satyam1203 I've opened a PR for this. please assign to me

**Comment by Satyam1203** [comment]
@ShaneCreedon You already made a PR, right? I'll merge it... No point in assigning it to you here and then go merge it.

**Comment by Ticketedmoon** [comment]
@Satyam1203 Okay that's perfect! https://github.com/Satyam1203/resume-github/pull/6
