### ISSUE TITLE
Feature: Show repository creation date for each repository beside the name

### ISSUE THREAD

**Issue by Ticketedmoon** [Satyam1203/resume-github#7]

**Comment by Ticketedmoon** [comment]
Changed this issue to be **creation date** as that would be more useful to an individual looking at the resume

**Comment by Ticketedmoon** [comment]
https://github.com/Satyam1203/resume-github/pull/8

**Comment by Satyam1203** [comment]
Doesn't sound good to me @ShaneCreedon

**Comment by Ticketedmoon** [comment]
@Satyam1203 How do you mean?

**Comment by Satyam1203** [comment]
The idea of having a date beside a repo will make things messy... Doesn't seem like a good idea

**Comment by Ticketedmoon** [comment]
@Satyam1203 Well it's up to you but the app just is showing 6 repositories for each resume anyway so it can't really get messy, its just a small additional text next to the name.
